unicef/etools-datamart

src/etools_datamart/apps/mart/data/models/location.py

Now updates/set on `batch_update_centroid` call

Add geonameid

---

src/etools_datamart/apps/mart/data/models/intervention.py

Use PartnersInterventionamendment model from intervention amendments

---

src/etools_datamart/apps/mart/data/models/partners_staffmember.py

Fix partner staff member loader

---

src/etools_datamart/apps/mart/data/models/fm_questions.py

Correct fmontract data loader, differently handling of many to many fields

---

src/etools_datamart/apps/mart/data/models/fm_questions.py

Fix fm question data loader

---

src/etools_datamart/apps/mart/data/models/fm_questions.py

Fix load fm ontract task

---

src/etools_datamart/apps/mart/data/models/fm_questions.py

Fix reference to method name in fm question loader

---

src/etools_datamart/config/settings.py

This was commented out and is related to the errors;
- https://excubo.unicef.io/sentry/datamart/issues/256/?query=is%3Aunresolved
- https://excubo.unicef.io/sentry/datamart/issues/261/?query=is%3Aunresolved

Add djcelery_email to INSTALLED_APPS

---

src/etools_datamart/apps/mart/data/admin.py
src/etools_datamart/config/settings.py

Also removed ADMINS from settings

Add admin engagements

---

src/etools_datamart/apps/mart/data/models/audit_engagement.py

Return params in correct order from _get_risk method

---

src/etools_datamart/apps/mart/data/models/fm_questions.py

Correct variable name in fmquestion loader

---

src/etools_datamart/apps/mart/data/models/fm_questions.py

Remove outcome from FMQuestion values dictionary

---

docker-compose.yml
src/unicef_rest_framework/renderers/xls.py

Hact History XLS Render Issue

---

src/etools_datamart/apps/mart/data/models/fm_questions.py

See https://excubo.unicef.io/sentry/datamart-dev/issues/1825/?query=is%3Aunresolved

Update collection_method mapping in FMQuestion loader

---

src/etools_datamart/apps/web/templates/rest_framework/base.html
src/unicef_rest_framework/models/export.py
src/unicef_rest_framework/tasks.py
src/unicef_rest_framework/templates/rest_framework/base.html

[ch24480] celery tasks issue

---

CHANGES
src/unicef_rest_framework/renderers/xls.py

[ch24871] xls export fix

---

src/etools_datamart/apps/mart/data/admin.py
src/etools_datamart/apps/mart/data/models/fm_questions.py
tests/_test_lib/test_utilities/factories/data.py
tests/etl/test_etl_loaders.py

[ch25208] fix fm question endpoint

---

src/etools_datamart/api/endpoints/datamart/attachment.py
tests/api/interfaces/_api_checker/test_data/test_list/_api_latest_datamart_attachment_attachment_/get/172c2ec1cbe8d30421fec878c7aa3d4ea0cc8703be8b14a633537a7df2f6c88f.response.json
tests/api/interfaces/_api_checker/test_data/test_list/_api_latest_datamart_partners_agreements_/get/197add8e52191fc33bc0669a32ea63213e8608ee9b3b24c42981397919aba411.response.json
tests/api/interfaces/_api_checker/test_data/test_record/_api_latest_datamart_partners_agreements_33_/get/dc937b59892604f5a86ac96936cd7ff09e25f18ae6b758e8014a24c7fa039e91.response.json

[ch25300] attachment etools minimal sync

---

src/etools_datamart/api/endpoints/datamart/trips.py
tests/api/interfaces/_api_checker/test_data/test_list/_api_latest_datamart_t2f_trips_/get/14b309a57e40077dd98db526a8e15c7e1296a4b12d15fecfed169a9e70bffa08.response.json

[ch25687] added trip light serializer

---

src/etools_datamart/apps/mart/data/models/attachments_attachment.py

[ch25710] attachment fix file type

---

CHANGES
src/etools_datamart/apps/mart/data/admin.py
src/etools_datamart/apps/mart/data/models/actionpoint.py
src/etools_datamart/apps/sources/etools/enrichment/consts.py

[ch25981] action points new modules

---

src/etools_datamart/apps/mart/data/models/attachments_attachment.py
src/etools_datamart/apps/mart/data/models/intervention.py
src/etools_datamart/apps/sources/etools/admin.py

[ch26042] fix attachments

---

src/etools_datamart/apps/mart/data/models/fm_questions.py

[ch26107] programme areas

---

src/etools_datamart/config/settings.py
src/unicef_rest_framework/models/export.py

[ch27402] export notification

---

src/etools_datamart/apps/sources/source_prp/api.py

[ch27403] progress-report-tweaks

---

CHANGES
src/etools_datamart/apps/mart/data/models/fm_questions.py

[ch28770] fm fix locations

---

src/etools_datamart/apps/multitenant/management/commands/inspectschema.py
src/etools_datamart/apps/multitenant/postgresql/introspection.py

[ch28811] update libs: fix collation error on inspectschema cmd

---

src/unicef_rest_framework/renderers/xls.py

[sentry-6455] fix xlsx export

---

src/etools_datamart/apps/mart/data/models/actionpoint.py

[ch33312] fix for action points endpoint t2f url to use travel.pk instead of travel_activity.pk

---

src/etools_datamart/apps/sources/etools/enrichment/partners_partnerorganization.py

[ch33313] correct min_req_spot_checks for Partners

---

src/etools_datamart/apps/mart/data/models/intervention_activity.py

[ch33320] fix on intervention-activity loader error

---

CONTRIBUTING.md
src/etools_datamart/apps/mart/data/models/intervention.py
src/etools_datamart/apps/mart/data/models/partner_hact.py
src/etools_datamart/apps/mart/data/models/travel_activity.py
src/etools_datamart/apps/mart/data/models/trip.py

[ch33571]
- includes revert tpmv query in partnerhact to original

ETL Intervetions sync only end_date 2y

---

src/etools_datamart/apps/mart/prp/models/datareport.py

[ch33615] PRP loader improve efficiency

---

src/etools_datamart/apps/mart/data/models/attachments_attachment.py
src/etools_datamart/apps/mart/prp/admin.py
src/etools_datamart/apps/mart/prp/models/indicator_by_location.py
src/etools_datamart/apps/mart/prp/models/indicator_report.py

[ch33615]
1. PRP indicator by location 
2. PRP indicator report 
3. eTools data attachments

 Loader efficiency 

---

src/etools_datamart/apps/mart/data/models/psea.py

[ch35061] fix load_data_pseaassessment etl task

---

src/etools_datamart/api/endpoints/datamart/fm_questions.py
src/etools_datamart/config/settings.py

[ch36256] Export 555 Fm Questions: added year filter for /fm-questions/

---

.circleci/config.yml
src/etools_datamart/__init__.py

-  Version is marked 
-  image is taged with specific

Mark version 4.7.6
